# Generated by Django 2.2.5 on 2019-09-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código Identificador')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do Cliente')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('collection_date', models.DateField(verbose_name='Data de Coleta')),
                ('delivery_date', models.DateField(verbose_name='Data de Entrega')),
                ('doctor_name', models.CharField(max_length=30, verbose_name='Nome do Médico')),
            ],
        ),
    ]
